# Generated by Django 5.1.5 on 2025-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('cardnumber', models.TextField(max_length=16)),
                ('cardccv', models.TextField(max_length=3)),
                ('cardexp', models.TextField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=9)),
                ('crust', models.CharField(max_length=11)),
                ('sauce', models.CharField(max_length=7)),
                ('cheese', models.CharField(max_length=11)),
                ('pepperoni', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('peppers', models.BooleanField(default=False)),
                ('mushrooms', models.BooleanField(default=False)),
                ('onions', models.BooleanField(default=False)),
            ],
        ),
    ]
