# Generated by Django 5.1.5 on 2025-02-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password2',
            new_name='password_again',
        ),
    ]
