# Generated by Django 5.1.5 on 2025-02-09 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pizza_crust_alter_pizza_sauce_alter_pizza_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cardnumber',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cardccv',
            new_name='ccv',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cardexp',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_and_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.TextField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ccv',
            field=models.TextField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='expiration_date',
            field=models.TextField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Vegan', 'Vegan'), ('Low Fat', 'Low Fat')], default='Mozzarella', max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Thin', 'Thin'), ('Thick', 'Thick'), ('Gluten Free', 'Gluten Free')], default='Normal', max_length=11),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
