# Generated by Django 5.1.5 on 2025-02-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cardnumber_customer_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ccv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='expiration_date',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='ccv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pizza'),
        ),
    ]
