# Generated by Django 5.1.5 on 2025-02-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_card_number_alter_customer_ccv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
