# Generated by Django 5.1.5 on 2025-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
