# Generated by Django 5.1.5 on 2025-02-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cheese_sauce_size_alter_pizza_cheese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Vegan', 'Vegan'), ('Low Fat', 'Low Fat')], default='Mozzarella', max_length=11),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('Tomato', 'Tomato'), ('BBQ', 'BBQ')], default='Tomato', max_length=11),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=11),
        ),
    ]
