# Generated by Django 5.1.5 on 2025-02-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pizza_cheese_alter_pizza_sauce_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cheese',
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
